server:
  port: 8081 #端口
spring:
  application:
    name: api-gateway-server #服务名称
  redis:
    host: localhost
    pool: 6379
    database: 0
  cloud: #配置SpringCloudGateway的路由
    gateway:
      routes:
        - id: product-service
          uri: lb://service-product
          predicates:
            - Path=/product-service/**
          filters:
           # - name: RequestRateLimiter
             # args:
                # 使用SpEL从容器中获取对象
              #  key-resolver: '#{@userkeyResolver}'
                # 令牌桶每秒填充平均速率
              #  redis-rate-limiter.replenishRate: 1
                # 令牌桶的上限
               # redis-rate-limiter.burstCapacity: 3
          - RewritePath=/product-service/(?<segment>.*), /$\{segment}
        - id: order-service
          uri: lb://service-order
          predicates:
            - Path=/order-service/**
          filters:
              # - name: RequestRateLimiter
              # args:
              # 使用SpEL从容器中获取对象
              #  key-resolver: '#{@userkeyResolver}'
              # 令牌桶每秒填充平均速率
              #  redis-rate-limiter.replenishRate: 1
              # 令牌桶的上限
              # redis-rate-limiter.burstCapacity: 3
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}
  zipkin:
    base-url: http://127.0.0.1:9411/  #zipkin server的请求地址
    sender:
      type: web  #请求方式,默认以http的方式向zipkin server发送追踪数据
  sleuth:
    sampler:
      probability: 1.0  #采样的百分比
#eureka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true #使用ip地址注册
logging:
level:
root: INFO
org.springframework.web.servlet.DispatcherServlet: DEBUG
org.springframework.cloud.sleuth: DEBUG