server:
  port: 7001 #服务端口
spring:
  application:
    name: rabbitmq-producer #指定服务名
  rabbitmq:
    addresses: 127.0.0.1
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        output:
          destination: itcast-default
        myoutput:
          destination: itcast-custom-default
          producer:
            partition-key-expression: payload
            partition-count: 2
      binders:
        defaultRabbit:
          type: rabbit